### ISSUE TITLE
Server won't start in development unless require false was added to the readme

### ISSUE THREAD

**Issue by FloHeinle** [analogeryuta/capistrano-sudo#2]
Hi analogeryuta,

I had to add require: false, otherwise the server wouldn't start in development.
`gem 'capistrano-sudo' require: false`

Error message without require false: 
/home/User/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-sudo-0.0.4/lib/capistrano/tasks/capistrano-sudo.rake:1:in `<top (required)>': undefined method `namespace' for main:Object (NoMethodError)

If you want, I can fork and adopt the readme.

Bests
Flo

**Comment by analogeryuta** [comment]
Hi @FloHeinle .

I fixed README as you suggested, so I close this issue.
Thank you for your comment.
